default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV["DATABASE"] %>
  host: <%= ENV["DATABASE_HOST"] %>
  port: <%= ENV["DATABASE_PORT"] %>
  pool: <%= ENV["DATABASE_POOL"] || 5 %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>

development:
  <<: *default

test:
  <<: *default
  database: fotoin_test

production:
  <<: *default

staging:
  <<: *default